### PR TITLE
feat: explore jobs and companies (2 separate pages)

### PR DESCRIPTION
**Pull request by vattevaii**

### CODE REVIEW

**Comment by anishjoshi1999** [comment]
image
@vattevaii Could you look into this? There is some misalignment between the search bar and the jobs of companies.

**Comment by anishjoshi1999** [comment]
There is another PR done, "Infinite Scroll Pagination," by Samir. Everything is working as expected, and I am going to accept it. We are getting some duplication of companies while implementing the pagination feature, so he is going to work on that.@vattevaii try to take a pull once before making any modifications.

**Comment by vattevaii** [comment]
@anishjoshi1999 above issue fixed

**Comment by anishjoshi1999** [comment]
@vattevaii Could you take the latest pull and resolve the conflict that was included in your PR and send the latest updated PR.

**Pull request closed without merging**
