### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by bmasmhj**
"Previously, the .htaccess file I provided doesn't seem to be working. Please try using this new one.

**Note: Don't forget to upload the .htaccess file to your root server**

### CODE REVIEW

**Comment by bmasmhj** [comment]
image

**Comment by anishjoshi1999** [comment]
but I am using render.com for deployment could you research on that
render

**Comment by vattevaii** [comment]
image
This will do

**Comment by bmasmhj** [comment]
Yup This worked for me too

> image This will do

**Comment by anishjoshi1999** [comment]
> Yup This worked for me too
> 
> > image This will do

This worked for me too. @bmasmhj, do we still need the.htacess file? I don't think we need it anymore.

**Comment by anishjoshi1999** [comment]
Thanks for the help guys @bmasmhj  @vattevaii I am going to close this PR now.

**Pull request closed without merging**
