### PR TITLE
feat(ui): infinite scroll pagination

### PR DESCRIPTION
**Pull request by samir-byte**
- infinite scroll pagination added to list all jobs
- package used https://www.npmjs.com/package/react-infinite-scroll-component
- couldnt test properly because of limited data

### CODE REVIEW

**Comment by anishjoshi1999** [comment]
image
image
image
@samir-byte Could you look into why we are getting duplicate companies, and please check on whether the pagination feature is integrated into the company job listing? else, everything seems to work.

**Comment by anishjoshi1999** [comment]
image
to test pagination i have done page size = 5 so that you could test

**Comment by anishjoshi1999** [comment]
feel free to browse the server code : https://github.com/anishjoshi1999/CodeCareerNepal-Server.git and align the frontend code accordingly

**Comment by vattevaii** [comment]
this pr and my pr have some conflicts.. @samir-byte @anishjoshi1999.
I have added separate jobs page (where we are listing out all jobs from all companies). we would need a separate jobs api. Also we would need to modify our search hook to work with apis rather than internal data

**Comment by anishjoshi1999** [comment]
> this pr and my pr have some conflicts.. @samir-byte @anishjoshi1999. I have added separate jobs page (where we are listing out all jobs from all companies). we would need a separate jobs api. Also we would need to modify our search hook to work with apis rather than internal data

I have open-sourced the backend; feel free to browse and modify it accordingly. It is pinned to my profile.

**Comment by samir-byte** [comment]
@vattevaii i am not supposed to rebase with feature branch code. I rebased with main branch and it is okay. Plus i am working according to opened issues.

**Comment by samir-byte** [comment]
@anishjoshi1999 compnay job listing seems to be filtered in frontend. We can keep frontend pagination but doesnt make much sense as long as we are not fetching company specific data from api. Apart from that duplicate issue has been fixed and updated in this pr

**Pull request merged**
